.TH VOIDTOOLS 1 "August 2025" "VOID Tools" "User Commands"

.SH NAME
voidtools \- Dispatcher for voidtools helper commands

.SH SYNOPSIS
.B voidtools
[\fICOMMAND\fR] [\fIOPTIONS\fR] [\fIINPUT\fR]

.SH DESCRIPTION
.B voidtools
is a command-line dispatcher for picoCTF helper utilities. It forwards commands to the appropriate sub-tool located in /usr/bin/. If no command is given or --help is specified, it displays usage information.

Available commands:
.TP
.B copy
Copy text to clipboard using xsel.
.TP
.B man <com>
Show the manual page for a subcommand (e.g., picofind).
.TP
.B --help
Show usage information.

.SH USAGE
.nf
$ voidtools <command> [options] [input]
.fi

.SH EXAMPLES
Show help:
.nf
$ voidtools --help
.fi

Copy text to clipboard:
.nf
$ voidtools copy "picoCTF{flag_here}"
.fi

.SH SEE ALSO
picofind(1), picoformat(1), picoflag(1), xsel(1)

.SH AUTHOR
Written by Mahros AL-Qabasy.
Email: mahros.elqabasy@gmail.com

.SH BUGS
Report issues at https://github.com/elqabasy/voidtools/issues